"""Generate rpcs3/Emu/RSX/Remix/RemixDemonsLights.inl from des_lights.json.

    python docs/remix/demons/gen_lights_inl.py

The table is keyed on the SCATTERING sun direction, because that is the one value the
backend already recovers live from the guest (constant c111, validated unit-length with
y<0 at the atmosphere draw). Matching it against this table identifies which authored
preset is on screen without hooking the game's level loader at all.

Only rows that author at least one non-zero light are emitted; the rest are unused preset
slots and would only add ambiguity to the match.
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, 'des_lights.json')
DST = os.path.join(HERE, '..', '..', '..', 'rpcs3', 'Emu', 'RSX', 'Remix', 'RemixDemonsLights.inl')


def f(x):
    return '%.6ff' % x


def main():
    data = json.load(open(SRC, encoding='utf-8'))
    rows = []
    for lv in sorted(data):
        if not lv.startswith('m'):
            continue
        for r in data[lv]['rows']:
            sky = r.get('sky')
            if not sky:
                continue
            lit = [d for d in r['dir'] if d['pct'] > 0]
            hemi = max(r['hemi_up'] + r['hemi_dn'])
            if not lit and hemi <= 0.0:
                continue
            rows.append((lv, r, sky))

    out = []
    out.append('// GENERATED by docs/remix/demons/gen_lights_inl.py -- do not edit by hand.')
    out.append('//')
    out.append("// Demon's Souls' own authored lighting, read out of the disc's DrawParam banks")
    out.append('// (PS3_GAME/USRDIR/param/drawparam/*.param). See docs/remix/demons/README.md for the')
    out.append('// format, the angle convention and the measurement that verifies it.')
    out.append('//')
    out.append('// sun[]      the LIGHT_SCATTERING_BANK sun travel vector - the MATCH KEY. The backend')
    out.append('//            recovers this live from guest constant c111, so a row is identified')
    out.append('//            without knowing which level is loaded.')
    out.append('// dir[k]     LIGHT_BANK directional light k: travel vector then radiance (rgb already')
    out.append('//            multiplied by the authored intensity percent). An all-zero radiance means')
    out.append('//            the preset does not author that light.')
    out.append('// hemi_up/dn the hemisphere ambient, as authored. A path tracer has no hemisphere')
    out.append('//            light, so the consumer approximates each half with a wide distant light;')
    out.append('//            that approximation is the consumer\'s, not this table\'s.')
    out.append('')
    out.append('namespace remix_rsx')
    out.append('{')
    out.append('\tstruct demons_light_preset')
    out.append('\t{')
    out.append('\t\tconst char* level;')
    out.append('\t\tunsigned row;')
    out.append('\t\tfloat sun[3];')
    out.append('\t\tfloat dir[3][3];')
    out.append('\t\tfloat rgb[3][3];')
    out.append('\t\tfloat hemi_up[3];')
    out.append('\t\tfloat hemi_dn[3];')
    out.append('\t};')
    out.append('')
    out.append('\tinline constexpr demons_light_preset s_demons_light_presets[] =')
    out.append('\t{')
    for lv, r, sky in rows:
        d = r['dir']
        out.append('\t\t{ "%s", %d,' % (lv, r['id']))
        out.append('\t\t\t{ %s },' % ', '.join(f(x) for x in sky['sun_travel']))
        out.append('\t\t\t{ %s },' % ', '.join('{ %s }' % ', '.join(f(x) for x in k['travel']) for k in d))
        out.append('\t\t\t{ %s },' % ', '.join('{ %s }' % ', '.join(f(x) for x in k['rgb']) for k in d))
        out.append('\t\t\t{ %s },' % ', '.join(f(x) for x in r['hemi_up']))
        out.append('\t\t\t{ %s } },' % ', '.join(f(x) for x in r['hemi_dn']))
    out.append('\t};')
    out.append('}')
    out.append('')

    with open(os.path.normpath(DST), 'w', encoding='utf-8', newline='\r\n') as fh:
        fh.write('\n'.join(out))
    print('wrote %s  (%d presets)' % (os.path.normpath(DST), len(rows)))


if __name__ == '__main__':
    sys.exit(main())
